---

packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - nginx
  - certbot
  - python3-certbot-nginx
  - nfs-common

grafana:
  - grafana
  - grafana-enterprise

grafana_domain_name: "grafana.example.com"
email_user: "roeeelnekave@gmail.com"
